<a href="https://colab.research.google.com/github/milica-golocorbin/math_for_dl/blob/main/Linear%20Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch
import tensorflow as tf

# Data Structures for Linear Algebra

## Tensors - Fundamental data structure

Tensors are array of numbers. Tensors are machine learning generalization of vectors and matrices to any number of dimensions.

- zero dimensional SCALAR tensor
- one dimensional VECTOR tensor
- two dimensional MATRIX tensor
- higher dimensional n TENSOR

In [64]:
# SCALAR TENSORS
# single number, no dimensions

# base python
num = 25
type(num)

# pytorch
num_pt = torch.tensor(25)
num_pt

# tensorflow
num_tf = tf.Variable(25)
num_tf

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=25>

In [65]:
# number of dimensions - pytorch
num_pt.shape

torch.Size([])

In [66]:
# number of dimensions - tensorflow
num_tf.shape

TensorShape([])

In [67]:
result = num_pt + num_tf
# result
result.numpy()

50

In [7]:
# VECTOR TENSORS
# one dimensional array of numbers(scalars)

# numpy
y = np.array([25, 2, 5])
y

# pytorch
y_pt = torch.tensor([25, 2, 5])
y_pt

# tensorflow
y_tf = tf.Variable([25, 2, 5])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

In [8]:
y.shape

(3,)

In [9]:
y[0]

25

## Tensor Transposition

Transpose converts column to row and vice versa.

**$(X^T)_i,_j = X_j,_i$**

In [10]:
# vector transposition
# row vector (1,3) -> column vector (3,1)

y_t = y.T
y_t

z = np.array([[25, 2, 3]])
z_t = z.T
z_t

array([[25],
       [ 2],
       [ 3]])

In [11]:
z_t.shape

(3, 1)

In [12]:
# MATRIX TENSORS
# two dimensional array of numbers(scalars)

# numpy
M = np.array([[25, 2], [5, 26], [3, 7]])
M

# pytorch
M_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
M_pt

# tensorflow
M_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
M_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [13]:
M.shape
# (row, column)

(3, 2)

In [14]:
M.size

6

In [15]:
M[:,0]
# first column

array([25,  5,  3])

In [16]:
M[1,:]
# second row

array([ 5, 26])

In [17]:
tf.rank(M_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [18]:
# matrix transposition

M.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [19]:
# matrix transposition pytorch

M_pt.T

tensor([[25,  5,  3],
        [ 2, 26,  7]])

In [20]:
# matrix transposition tensorflow

tf.transpose(M_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]], dtype=int32)>

In [28]:
y

array([25,  2,  5])

In [26]:
# arithmetic operations
#vectors
y * 2

array([50,  4, 10])

In [30]:
y + 2

array([27,  4,  7])

In [29]:
M

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [27]:
# arithmetic operations
#matrix
M * 2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [31]:
M + 2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [32]:
# with pytorch

M_pt * 2

tensor([[50,  4],
        [10, 52],
        [ 6, 14]])

In [33]:
torch.add(M_pt, 2)

tensor([[27,  4],
        [ 7, 28],
        [ 5,  9]])

In [34]:
torch.mul(M_pt, 2)

tensor([[50,  4],
        [10, 52],
        [ 6, 14]])

In [35]:
# with tensorflow

M_tf * 2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[50,  4],
       [10, 52],
       [ 6, 14]], dtype=int32)>

In [36]:
tf.add(M_tf, 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[27,  4],
       [ 7, 28],
       [ 5,  9]], dtype=int32)>

In [38]:
tf.multiply(M_tf, 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[50,  4],
       [10, 52],
       [ 6, 14]], dtype=int32)>

## HADAMARD PRODUCT

If two tensors have same size, we multiply element by element. It is element wise product.

$A \odot X$

In [41]:
A = M + 2

A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [42]:
M

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [43]:
A + M

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [44]:
# HADAMARD PRODUCT
A * M

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [ ]:
# Same in PyTorch and TensorFlow.

## REDUCTION

Calculating the sum across all elements of a tensor.

- For vector **x** of length *n*, we calculate: 

  $\sum^n_{i=1} x_i$

  $x_i$ refers to all of the elements from the first element(i=1), to the $n^{th}$ one. Sigma($\sum$) means sum.

- For matrix **X** with *m* by *n* dimensions, we calcualte:

   $\sum^m_{i=1} \sum^n_{j=1} X_{i,j}$

Basically with this formula we are saying **sum all elements**. Reduce to total.

In [45]:
y

array([25,  2,  5])

In [46]:
y.sum()

32

In [47]:
M

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [48]:
M.sum()

68

In [51]:
torch.sum(y_pt)

tensor(32)

In [50]:
torch.sum(M_pt)

tensor(68)

In [53]:
tf.reduce_sum(y_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [54]:
tf.reduce_sum(M_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=68>

In [57]:
# Sum only axis

M.sum(axis=0)
# summing columns

array([33, 35])

In [58]:
# Sum only axis

M.sum(axis=1)
# summing rows

array([27, 31, 10])

In [60]:
torch.sum(M_pt, 0)

tensor([33, 35])

In [61]:
tf.reduce_sum(M_tf, 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 31, 10], dtype=int32)>

## DOT PRODUCT

It is like combination of HADAMARD PRODUCT and REDUCTION.

If we have two vectors(x,y) with the same length, we can calculate dot product between them. This is annotated by:

- $x * y$
- $x^T y$
- $<x,y>$

We calculate products in an element-wise and then sum reductively across the procucts to scalar value.

$x * y = \sum^n_{i=1} x_iy_i$

for first element of x and for the first element of y, we calculate the product(we multiply them) and we do that for the second, all the way up to up to $n^{th}$ element of x by $n^{th}$ element of y. Once we have all of the products, we than sum up, $\sum$.

DOT PRODUCT IS PERFORMED AT EVERY ATRIFICIAL NEURON IN A DEEP NEURAL NETWORK.

In [63]:
y

array([25,  2,  5])

In [68]:
x = np.array([0,1,2])
x

array([0, 1, 2])

In [69]:
# manual dot product
res = 25 * 0 + 2 * 1 + 5 * 2
res

12

In [70]:
# dot product numpy
np.dot(x,y)

12

In [71]:
y_pt

tensor([25,  2,  5])

In [72]:
x_pt = torch.tensor([0,1,2])
x_pt

tensor([0, 1, 2])

In [73]:
# dot product pytorch

res_pt = torch.dot(y_pt, x_pt)
res_pt

tensor(12)

In [76]:
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

In [74]:
x_tf = tf.Variable([0,1,2])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

In [79]:
# # dot product tensorflow (doesn't have dot)
res_tf = tf.reduce_sum(tf.multiply(x_tf, y_tf))
res_tf

<tf.Tensor: shape=(), dtype=int32, numpy=12>