<a href="https://colab.research.google.com/github/milica-golocorbin/math_for_dl/blob/main/MathForDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import torch
import tensorflow as tf

# Data Structures for linear algebra

## Tensors - Fundamental data structure

Tensors are array of numbers. Tensors are machine learning generalization of vectors and matrices to any number of dimensions.

- zero dimensional SCALAR tensor
- one dimensional VECTOR tensor
- two dimensional MATRIX tensor
- higher dimensional n TENSOR

In [8]:
# SCALAR TENSORS
# single number, no dimensions

# base python
x = 25
type(x)

# pytorch
x_pt = torch.tensor(25)
x_pt

# tensorflow
x_tf = tf.Variable(25)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=25>

In [6]:
# number of dimensions - pytorch
x_pt.shape

torch.Size([])

In [9]:
# number of dimensions - tensorflow
x_tf.shape

TensorShape([])

In [12]:
result = x_pt + x_tf
# result
result.numpy()

50

In [24]:
# VECTOR TENSORS
# one dimensional array of numbers(scalars)

# numpy
y = np.array([25, 2, 5])
y

# pytorch
y_pt = torch.tensor([25, 2, 5])
y_pt

# tensorflow
y_tf = tf.Variable([25, 2, 5])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

In [25]:
y.shape

(3,)

In [26]:
y[0]

25

In [18]:
# vector transposition
# row vector (1,3) -> column vector (3,1)

y_t = y.T
y_t

z = np.array([[25, 2, 3]])
z_t = z.T
z_t

array([[25],
       [ 2],
       [ 3]])

In [19]:
z_t.shape

(3, 1)

In [36]:
# MATRIX TENSORS
# two dimensional array of numbers(scalars)

# numpy
M = np.array([[25, 2], [5, 26], [3, 7]])
M

# pytorch
M_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
M_pt

# tensorflow
M_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
M_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [29]:
M.shape
# (row, column)

(3, 2)

In [30]:
M.size

6

In [31]:
M[:,0]
# first column

array([25,  5,  3])

In [34]:
M[1,:]
# second row

array([ 5, 26])

In [37]:
tf.rank(M_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>