In [2]:
import numpy as np
import torch

In [12]:
# USING NUMPY
# create a vector
nv = np.array([[1,2,3,4]])
print(nv)

# transpose it
nv_T = nv.T
print(nv_T)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [7]:
# create a matrix
nM = np.array([[1,2,3],[4,5,6]])
print(nM)

# transpose it
nM_T = nM.T
print(nM_T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [11]:
# USING PYTORCH
# create a vector
tv = torch.tensor([[1,2,3,4]])
print(tv)

# transpose it
tv_T = tv.T
print(tv_T)

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [13]:
# create a matrix
tM = torch.tensor([[1,2,3],[4,5,6]])
print(tM)

# transpose it
tM_T = tM.T
print(tM_T)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [18]:
# USING NUMPY
# DOT product

nv1 = np.array([1,2,3,4])
nv2 = np.array([0,1,0,-1])

np_d = np.dot(nv1, nv2)
print(np_d)

print(np.sum(nv1*nv2))

-2
-2


In [20]:
# USING PYTORCH
# DOT product

tv1 = torch.tensor([1,2,3,4])
tv2 = torch.tensor([0,1,0,-1])

tv_d = torch.dot(tv1, tv2)
print(tv_d)

print(torch.sum(tv1*tv2))

tensor(-2)
tensor(-2)


In [26]:
#USING NUMPY
# MATRIX MULTIPLICATION(ordered dot product)

A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)
# print(A)
# print(B)
# print(C)

# multiplication
x = np.matmul(A,B)
x1 = A@B
print(np.round(x, 2))
print(np.round(x1, 2))

[[-0.69  0.65  0.71 -0.08 -0.66]
 [-0.84  0.66  0.94  0.21 -1.7 ]
 [ 1.32 -1.57 -1.19 -0.06  0.19]]
[[-0.69  0.65  0.71 -0.08 -0.66]
 [-0.84  0.66  0.94  0.21 -1.7 ]
 [ 1.32 -1.57 -1.19 -0.06  0.19]]


In [28]:
#USING PYTORCH
# MATRIX MULTIPLICATION(ordered dot product)

A = torch.randn(3,4)
B = torch.randn(4,5)
C = torch.randn(4,7)

print(np.round(A@C, 2))

tensor([[-1.4000,  0.5800, -0.2100, -0.9100, -1.5200,  0.6800, -0.9200],
        [-0.9100, -2.4100,  0.9300,  0.5300, -1.3000, -0.4300, -3.4500],
        [ 2.5800,  4.1600,  0.5100, -1.0100,  1.7100,  0.1600, -1.6800]])
